class MyLocalization {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'tr': {
      '1': 'invoiceStatus=0 iken başarılı işlem',
      '200': 'İptal işlemi başarılı',
      '500': 'Hata',
      '3000': 'Nakit Fatura oluşturulurken hata alınması',
      '3001': 'Kredi Fatura oluşturulurken hata alınması',
      '3002': 'SendAdvice başarılı olma durumu (QR işlem için)',
      '3003': 'Advice sonrası fatura hatalarının oluşması durumu',
      '3004': 'Advice hata durumu',
      '3005': 'Banka hata durumu 1',
      '3006': 'Banka başarılı durumu',
      '3007': 'Banka hata durumu 2',
      '3008': 'Istanbulkart ödeme başarılı durumu',
      '3009': 'Istanbulkart ödeme başarısız durumu',
      '3010': 'Fatura oluşturma nakit başarılı durumu',
      '3011': 'MKE satış fatura oluşturma hata durumu',
      '3012': 'MKE satış advice hata durumu',
      '3013': 'MKE satış banka hata durumu',
      '3014': 'Mke satış delete hata durumu',
      '3015': 'MKE satış banka hata durumu 1',
      '3016': 'MKE satış banka başarılı durumu',
      '3017': 'MKE satış banka hata durumu 2',
      '3018': 'Provizyon Kapama banka hata durumu 1',
      '3019': 'Provizyon Kapama banka başarılı durumu',
      '3020': 'Provizyon Kapama banka hata durumu 2',
      '3021': 'Provizyon Kapama advice hata durumu',
      '3022': 'Provizyon Kapama fatura oluşturma hata durumu',
      '3030': 'Puan sorgu banka hata durumu 1',
      '3031': 'Puan sorgu banka başarılı durumu',
      '3032': 'Puan sorgu banka hata durumu 2',
      '3033': 'Taksitli Satış banka hata durumu 1',
      '3034': 'Taksitli Satış banka başarılı durumu',
      '3035': 'Taksitli Satış banka hata durumu 2',
      '3036': 'Taksitli Satış advice hata durumu',
      '3037': 'Taksitli Satış fatura oluşturma hata durumu',
      '3038': 'Puan Kullanım banka hata durumu 1',
      '3039': 'Puan Kullanım banka başarılı durumu',
      '3040': 'Puan Kullanım banka hata durumu 2',
      '3041': 'Puan Kullanım advice hata durumu',
      '3042': 'Puan Kullanım fatura oluşturma hata durumu',
      '3043': 'Batch Dışı Provizyon Acma banka hata',
      '3044': 'Batch Dışı Provizyon Acma banka başarılı',
      '3045': 'Batch Dışı Provizyon Acma banka hata',
      '3046': 'Provizyon Açma banka hata durumu 1',
      '3047': 'Provizyon Açma banka başarılı durumu',
      '3048': 'Provizyon Açma banka hata durumu 2',
      '3049': 'Provizyon Açma advice hata durumu',
      '3050': 'Eşlenikli iade banka hata durumu 1',
      '3051': 'Eşlenikli iade banka başarılı durumu',
      '3052': 'Eşlenikli iade banka hata durumu 2',
      '3053': 'Eşlenikli iade fatura iptal hata durumu',
      '3054': 'Eşleniksiz iade banka hata durumu 1',
      '3055': 'Eşleniksiz iade banka başarılı durumu',
      '3056': 'Eşleniksiz iade banka hata durumu 2',
      '3058': 'İptal edilecek işlemin bulunamaması',
      '3059': 'Fatura iptal nakit başarılı durumu',
      '3060': 'Fatura iptal edilirken hata alınması',
      '3061': 'İptal banka hatası 1',
      '3062': 'İptal banka başarılı',
      '3063': 'İptal banka hatası 2',
      '3064': 'Istanbulkart iptal işlem başarılı',
      '3065': 'Istanbulkart iptal işlem başarısız',
      '3067': 'MKE iptal advice başarısız',
      '3068': 'MKE iptal banka hata durumu',
      '3069': 'MKE fatura iptal hata durumu',
      '3070': 'MKE iptal banka hata durumu 1',
      '3071': 'MKE iptal banka başarılı durumu',
      '3072': 'MKE iptal banka hata durumu 2',
      '3073': 'Ön provizyon kapama esnasında fatura oluşturulurken hata alınması',
      '3074': 'Teknik iptal tamamlanma aşamasında fatura iptalinde hata alınması',
      '3075': 'Taskitli satış fatura oluşturulurken hata alınması',
      '3076': 'Puan kullanımı fatura oluşturulurken hata alınması',
      '3077': 'Teknik iptal başlangıcında fatura iptalinden hata alınması',
      '3078': 'Teknik iptal backend bildirimi esnasında fatura iptalinde hata alınması',
      '3079': 'Offline işlem başarılı gönderim',
      '3080': 'Offline işlem iptalinde banka bildiriminin başarılı olması',
      '3081': 'İptal İşleminin Başarısız Olması',
      '3082': 'İptal İşleminin Başarılı Olması 2',
      '3083': 'İptal İşleminin Başarısız Olması 3',
      '3084': 'Offline İşlemin Başarılı Olarak Tamamlanması',
      '3085': 'Offline İşlemin Başarısız Olarak Tamamlanması',
      '3086': 'Satış Dışındaki Offline İşlemin Başarılı Olması',
      '3087': 'Satış ve İptal Dışındaki İşlemlerde Başarısız Olunması',
      '3091': 'Offline İşlem Başarılı Tamamlandı',
      '3092': 'Satış MKE Başarısız Olması',
      '3093': 'Satış MKE Başarılı Olunması',
      '3094': 'Satış MKE Başarısız Olması 2',
      '3095': 'Provizyon Kapama Offline Başarılı',
      '3096': 'Puan Sorgu Oflline Başarılı',
      '3097': 'Offline Puan Kullanım Başarılı',
      '3098': 'Batch Dışı Ön provizyon Açma Offline Başarılı',
      '3099': 'Offline Provizyon Açma Başarılı',
      '3100': 'Offline İade Başarılı',
      '3101': 'Offline Eşleniksiz İade Başarılı',
      '3102': 'Offline İşlem İptalinin Başarılı Bildirimi (Banka)',
      '3103': 'İstanbul Kart İle İptal İşleminin Backend Bildirimi Esnasında Hata Alması',
      '3104': 'Taksitli Satış Offline Başarılı',
      'hata_olustu': 'Hata oluştu',
    },
    'en': {
      '1': 'Successful transaction when invoiceStatus=0',
      '200': 'Cancellation successful',
      '500': 'Mistake',
      '3000': 'Error received while creating Cash Invoice',
      '3001': 'Receiving an error while creating a Credit Invoice',
      '3002': 'SendAdvice success status (for QR transaction)',
      '3003': 'Situation where invoice errors occur after advice',
      '3004': 'Advice error status',
      '3005': 'Bank error status 1',
      '3006': 'Bank successful status',
      '3007': 'Bank error status 2',
      '3008': 'Istanbulkart payment successful status',
      '3009': 'Istanbulkart payment failed status',
      '3010': 'Invoice creation cash successful status',
      '3011': 'MKE sales invoice creation error status',
      '3012': 'MKE sales advice error status',
      '3013': 'MKE sales bank error status',
      '3014': 'Mke sales delete error status',
      '3015': 'MKE sales bank error status 1',
      '3016': 'MKE sales bank successful status',
      '3017': 'MKE sales bank error status 2',
      '3018': 'Provision Closing bank error status 1',
      '3019': 'Provision Closing bank success status',
      '3020': 'Provision Closing bank error status 2',
      '3021': 'Provisioning Closing advice error status',
      '3022': 'Provision Closing invoice creation error status',
      '3030': 'Point query bank error status 1',
      '3031': 'Score query bank successful status',
      '3032': 'Point query bank error status 2',
      '3033': 'Installment Sales bank error status 1',
      '3034': 'Installment Sale bank successful status',
      '3035': 'Installment Sales bank error status 2',
      '3036': 'Installment Sales advice error status',
      '3037': 'Installment Sales invoice creation error status',
      '3038': 'Point Usage bank error status 1',
      '3039': 'Points Usage bank successful status',
      '3040': 'Point Usage bank error status 2',
      '3041': 'Points Usage advice error status',
      '3042': 'Point Usage invoice creation error status',
      '3043': 'Out of Batch Provision Opening bank error',
      '3044': 'Out of Batch Provision Opening bank is successful',
      '3045': 'Out of Batch Provision Opening bank error',
      '3046': 'Provision Opening bank error status 1',
      '3047': 'Provision Opening bank success status',
      '3048': 'Provision Opening bank error status 2',
      '3049': 'Provision Opening advice error status',
      '3050': 'Conjugated return bank error status 1',
      '3051': 'Conjugated return bank success status',
      '3052': 'Conjugated return bank error status 2',
      '3053': 'Conjugate return invoice cancellation error status',
      '3054': 'Unmatched return bank error status 1',
      '3055': 'Unconjugated return bank success status',
      '3056': 'Unmatched return bank error status 2',
      '3058': 'The transaction to be canceled cannot be found',
      '3059': 'Invoice cancellation cash successful status',
      '3060': 'Error received while canceling the invoice',
      '3061': 'Cancellation bank error 1',
      '3062': 'Cancellation bank successful',
      '3063': 'Cancellation bank error 2',
      '3064': 'Istanbul card cancellation process was successful',
      '3065': 'Istanbul card cancellation process failed',
      '3067': 'MKE cancellation advice failed',
      '3068': 'MKE canceled bank error status',
      '3069': 'MKE invoice cancellation error status',
      '3070': 'MKE canceled bank error status 1',
      '3071': 'MKE canceled bank successful status',
      '3072': 'MKE canceled bank error status 2',
      '3073': 'An error is received while creating an invoice during pre-authorization closing',
      '3074': 'Receiving an error in invoice cancellation during the technical cancellation completion phase',
      '3075': 'Error received while creating Taskit sales invoice',
      '3076': 'Receiving an error when creating an invoice for point usage',
      '3077': 'Error received from invoice cancellation at the beginning of technical cancellation',
      '3078': 'Error received in invoice cancellation during technical cancellation backend notification',
      '3079': 'Offline transaction successful sending',
      '3080': 'Successful bank notification for offline transaction cancellation',
      '3081': 'Failure of Cancellation',
      '3082': 'Successful Cancellation 2',
      '3083': 'Cancellation Failure 3',
      '3084': 'Successful Completion of Offline Transaction',
      '3085': 'Unsuccessful Completion of Offline Transaction',
      '3086': 'Success of Offline Transactions Other than Sales',
      '3087': 'Failure to Transactions Other than Sale and Cancellation',
      '3091': 'Offline Transaction Completed Successfully',
      '3092': 'Failure of Sales MKE',
      '3093': 'Being Successful in Sales MKE',
      '3094': 'Sales MKE Failure 2',
      '3095': 'Provisioning Closing Offline Successful',
      '3096': 'Score Query Oflline Successful',
      '3097': 'Offline Point Usage Successful',
      '3098': 'Opening Non-Batch Pre-authorization Offline Successful',
      '3099': 'Opening Offline Provision Successful',
      '3100': 'Offline Return Successful',
      '3101': 'Offline Unmatched Return Successful',
      '3102': 'Successful Notification of Offline Transaction Cancellation (Bank)',
      '3103': 'Cancellation Transaction with Istanbul Card Receives Error During Backend Notification',
      '3104': 'Installment Sales Offline Successful',
      'hata_olustu': 'An error occurred',
    },
  };

  static String translate(String key, String lang) {
    return _localizedStrings[lang]?[key] ?? key;
  }
}
